name: boxting
description: A new Flutter project.
version: 1.0.0+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State managment
  provider: ^4.3.2+2
  flutter_hooks: ^0.14.1

  # UI
  ff_navigation_bar: ^0.1.4
  cool_alert: ^1.0.1
  modal_bottom_sheet: ^1.0.0+1
  lottie: ^0.7.0+1
  cupertino_icons: ^0.1.3

  # Network
  dio: ^3.0.10
  retrofit: ^1.3.4+1
  json_annotation: ^3.1.1
  connectivity: ^2.0.2
  flutter_html: ^1.0.2

  # Local storage/auth
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  flutter_secure_storage: ^3.3.5
  local_auth: ^0.6.3+1
  package_info: ^0.4.0+16
  intl: 0.16.1

  # DI
  get_it: ^5.0.4

  # Firebase
  firebase_core: "^0.5.3"
  firebase_remote_config: "^0.4.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Launcher icon
  flutter_launcher_icons: ^0.8.1

  # Lint rules
  pedantic: ^1.9.0

  # Code generation
  json_serializable: ^3.5.0
  build_runner: ^1.4.0
  retrofit_generator: ^1.3.8+5

  # Testing
  mock_web_server: ^4.1.1
  mockito: ^4.1.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/boxting_logo_blue.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/biometric/
    - assets/lottie/
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-Regular.ttf
          style: normal
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-Black.ttf
        - asset: fonts/ProductSans-Bold.ttf
