name: boxting
description: Electronic voting application.
version: 1.0.0+41

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: 3.19.3


dependencies:
  flutter:
    sdk: flutter

  # State managment
  equatable: 2.0.5
  flutter_hooks: 0.20.5
  hooks_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  provider: ^6.1.2

  # UI
  modal_bottom_sheet: ^3.0.0
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  flutter_datetime_picker_plus: ^2.2.0


  # Network
  dio: ^5.4.3+1
  retrofit: 4.1.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.3
  flutter_html: 3.0.0-beta.2

  # Local storage/auth
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0
  package_info_plus: ^8.0.0
  intl: ^0.19.0

  # DI
  get_it: ^7.7.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_remote_config: ^5.0.0

  introduction_screen: ^3.1.14
  quickalert: ^1.1.0
  go_router: ^14.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Launcher icon
  flutter_launcher_icons: 0.13.1

  # Code generation
  json_serializable: ^6.8.0
  build_runner: ^2.1.11
  retrofit_generator: 8.1.0
  riverpod_generator: 2.4.0
  custom_lint: 0.6.4
  riverpod_lint: 2.3.10

  # Testing
  mockito: 5.4.4
  monarch: ^3.0.0
  state_notifier_test: ^0.0.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/boxting_logo_blue.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/biometric/
    - assets/lottie/
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Light.ttf
        - asset: fonts/ProductSans-Regular.ttf
          style: normal
        - asset: fonts/ProductSans-Medium.ttf
        - asset: fonts/ProductSans-Black.ttf
        - asset: fonts/ProductSans-Bold.ttf
