source "https://rubygems.org"

gem "fastlane"
source "https://rubygems.pkg.github.com/tianhaoz95" do
    gem "fastlane-plugin-flutter_version", "1.0.0"
  end


plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
