// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQEDUpk1P6_ckXGhTreX-osivpcC483F4',
    appId: '1:477434757501:android:5df5016becf157992acc14',
    messagingSenderId: '477434757501',
    projectId: 'boxting-8ec66',
    databaseURL: 'https://boxting-8ec66.firebaseio.com',
    storageBucket: 'boxting-8ec66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB58-4rtz314AzczWUAvVr8qTXFBlxc8mg',
    appId: '1:477434757501:ios:a51229a2beb73a312acc14',
    messagingSenderId: '477434757501',
    projectId: 'boxting-8ec66',
    databaseURL: 'https://boxting-8ec66.firebaseio.com',
    storageBucket: 'boxting-8ec66.appspot.com',
    androidClientId: '477434757501-p4a760p8ppiusodgb7lmlp4n5ssngfk3.apps.googleusercontent.com',
    iosClientId: '477434757501-u53lc4bhrumglgdr0jjrg3pg0ipfje7q.apps.googleusercontent.com',
    iosBundleId: 'com.boxtinglabs.boxting',
  );
}
